[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
#runner = "espflash flash --monitor --log-format defmt"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  "-C", "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core", "alloc"]

[env]
ESP_LOG="info"
DEFMT_LOG="info"
